spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/code-sharing?user=postgres&password=postgres}
    initialization-mode: always
    continue-on-error: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
